name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build and test stage combined in one job in order to save time because each
  # job runs in a separate runner which has to pull the dependencies each time
  # which takes a lot of time. And the caching does not properly work (at least
  # for me).
  # TODO: Cache docker image layers + haskell/stack dependencies
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: |
             sudo apt-get install -y qemu-system-arm
             sudo apt-get install -y python3-pip
             pip install pytest
             pip install pexpect

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build apps for platforms
        working-directory: ./src
        run: ./build.sh
      
      - name: Test apps for platforms
        working-directory: ./src
        run: ./test.sh
